services:
  db:
    image: ghcr.io/openimis/openimis-pgsql:${DB_TAG:-latest}
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - DEMO_DATASET=${DEMO_DATASET}
      - DB_ENGINE=django.db.backends.postgresql
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    networks:
      openimis-net:
