x-api: &default-api
  image: ghcr.io/openimis/openimis-be:${BE_TAG:-develop}
  environment:
    - DB_DEFAULT=${DB_DEFAULT:-postgresql}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_NAME=${DB_NAME}
    - DB_USER=${DB_USER}
    - DB_PASSWORD=${DB_PASSWORD}
    - SECRET_KEY=${SECRET_KEY}
    - SITE_ROOT=api
    - SITE_URL=${DOMAIN}
    - CELERY_BROKER_URL=amqp://rabbitmq
    - MODE=${MODE:-Prod}
    - HOSTS=${HOSTS}
    - CACHE_BACKEND=${CACHE_BACKEND}
    - CACHE_URL=${CACHE_URL}
    - CACHE_OPTIONS=${CACHE_OPTIONS}
    - OPENSEARCH_ADMIN=${OPENSEARCH_ADMIN}
    - OPENSEARCH_PASSWORD=${OPENSEARCH_PASSWORD}
    - OPENSEARCH_HOSTS=${OPENSEARCH_HOSTS}
  volumes:
    - photos:/openimis-be/openIMIS/images/insurees
   # - ./be.openimis.json:/openimis-be/openimis.json
  depends_on:
    db:
      condition: service_healthy
  networks:
    openimis-net:

services:
  frontend:
    image: ghcr.io/openimis/openimis-fe:${FE_TAG:-develop}
    restart: always
    environment:
      - REACT_APP_API_URL=api
      - NEW_OPENIMIS_HOST=${DOMAIN}
      - OPENIMIS_CONF_JSON=${OPENIMIS_FE_CONF_JSON}
      - OPENSEARCH_BASIC_TOKEN=${OPENSEARCH_BASIC_TOKEN}
    networks:
      proxy:
      openimis-net:
    depends_on:
      - backend
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
      # - ./fe.openimis.json:/app/openimis.json
      # comment the following line if you are using your own gateway
      # - ./conf/nginx:/conf/
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    labels:
      - traefik.enable=true
      - traefik.http.routers.${PROJECT_NAME}.rule=Host("${DOMAIN}")
      - traefik.http.routers.${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.${PROJECT_NAME}.tls=true
      - traefik.docker.network=proxy
      - traefik.http.services.${PROJECT_NAME}.loadbalancer.server.port=80

      - ./conf/nginx:/conf/
  migrations:
    <<: *default-api
    command: init
    restart: no
  backend:
    <<: *default-api
    command: start
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
  worker:
    <<: *default-api
    command: worker
    restart: always
    depends_on:
      migrations:
        condition: service_completed_successfully
    deploy:
      mode: replicated
      replicas: ${WORKER_REPLICAS:-3}
  opensearch-init:
    <<: *default-api
    entrypoint: ["/entrypoint-init-opensearch.sh"]
    command: []
    depends_on:
      - db
      - backend
      - opensearch
    volumes:
      - ./entrypoint-init-opensearch.sh:/entrypoint-init-opensearch.sh:ro
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
      openimis-net:
networks:
  openimis-net:
    name: "${PROJECT_NAME:-openimis}-net"
  proxy:
    external: true
volumes:
  database:
  photos:
