FROM nginx:latest

# Install gettext for envsubst
RUN apt-get update && apt-get install -y gettext-base

# Copy the entrypoint script
COPY docker-nginx-entrypoint.sh /docker-nginx-entrypoint.sh

# Copy the nginx.conf template
COPY nginx-dev.conf.template /etc/nginx/conf.d/default.conf.template
RUN chmod +x /docker-nginx-entrypoint.sh

CMD ["/docker-nginx-entrypoint.sh"]
