include: 
  - path: docker-compose.yml
    env_file: .env
  - path: docker-compose.openSearch.yml
    env_file: 
     - .env  
     - .env.openSearch
  - path: docker-compose.lightning.yml
    env_file: 
     - .env 
     - .env.lightning
      
 



