FROM nginx:latest

# Install gettext for envsubst
RUN apt-get update && apt-get install -y gettext-base

# Copy the entrypoint script
COPY opensearch-configuration/docker-nginx-entrypoint.sh /docker-nginx-entrypoint.sh

# Copy the nginx.conf template
COPY opensearch-configuration/nginx.conf.template /etc/nginx/conf.d/default.conf.template
RUN chmod +x /docker-nginx-entrypoint.sh

CMD ["/docker-nginx-entrypoint.sh"]
